[package]
name = "adventofcode2019"
version = "0.1.0"
authors = ["Lathentar <rccorn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
permutohedron = "0.2.4"
nalgebra = "0.18"
num = "0.2.0"